{
 "title": "Talk Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Performance (Gateway)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_bucket{status_code=\"200\", job=\"gateway-exporter\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Performance (Workers)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_bucket{IsSuccessful=\"True\", job=\"workers-exporter\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Gateway Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (irate(request_duration_seconds_bucket{job=\"gateway-exporter\"}[$__interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Workers success",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (IsSuccessful) (irate(request_duration_seconds_bucket{job=\"workers-exporter\"}[$__interval]))",
     "legendFormat": "{{IsSuccessful}}"
    }
   ]
  }
 ]
}